server:
  port: 8082
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/orders
    password: admin123
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: 'update'
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
